### ISSUE TITLE
Deletion of Campground Comments is not Available

### ISSUE THREAD

**Issue by hitechgeek** [hitechgeek/abhi-camp#2]
Deletion of Campground Comments is not Available
Could only be deleted by the author of the comments

**Comment by foreverabhi2002** [comment]
I have really understood the Project. Also got the fix for the bug @hitechgeek

**Comment by hitechgeek** [comment]
It's an open-source project so you can make a pull request.

**Comment by hitechgeek** [comment]
Issue resolved by @foreverabhi2002
